[project]
authors = ["Stephanie Bohaczuk <stephanie.bohaczuk@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "QC pipeline for DAF-seq. Template from Mitchell Vollger"
name = "dafqc"
platforms = ["osx-64", "linux-64"]
version = "0.0.1"

[tool.ruff.lint]
builtins = ["snakemake"]


[tasks]
fmt = "ruff format . && taplo format pixi.toml && snakefmt workflow/"
test-data = { cmd = [
    "cd",
    "$INIT_CWD",
    "&&",
    "mkdir",
    "-p",
    "dafqc-test-data",
    "&&",
    "aws",
    "s3",
    "--no-sign-request",
    "sync",
    "--endpoint-url",
    "https://s3.kopah.orci.washington.edu",
    "s3://bohaczuk/web/public/dafqc-test-data",
    "dafqc-test-data/",
] }
test = { cmd = [
    "cd",
    "$INIT_CWD/dafqc-test-data",
    "&&",
    "snakemake",
    "-s",
    "$PIXI_PROJECT_ROOT/workflow/Snakefile",
    "--configfile",
    "test.yaml",
    "-k",
], depends-on = [
    "test-data",
] }
snakemake = { cmd = "cd $INIT_CWD && snakemake -s $PIXI_PROJECT_ROOT/workflow/Snakefile" }


[dependencies]
conda = "*"
snakemake = "==8.21"
snakefmt = "*"
ruff = "*"
taplo = "*"
snakemake-executor-plugin-slurm = "*"
awscli = "2.22.*"
