ref: /mmfs1/gscratch/stergachislab/assemblies/hg38.analysisSet.fa # path to a reference fasta
manifest: config/config.tbl # table with samples to process. bam files should only include reads from a single PCR amplification.
dup_end_length: 8000 # length to consider for deduplication
dup_min_id_perc: 99.2 # minimum identity percentage required to mark duplicates